name: Deployment

on:
  push:
    branches: [ master ]

jobs:
  
  build:
    
    runs-on: ubuntu-latest

    steps:
  
    - uses: actions/checkout@v2

    - name: Installing Node.js
      run: actions/setup-node@v2-beta
      with: node-version: 12

    - name: Installing yarn
      run:  borales/actions-yarn@v2.0.0
      with: 
        cmd: install
        
    - name: Build React App
    	run: yarn build
      
    - name: Install Surge
	    run: npm install --global surge
      
    - name: Run surge
    	run: surge ./build first_react_faizan.surge.sh --token${{ secrets.SURGE_TOKEN }}
